/**:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    omni_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

omni_wheel_controller:
  ros__parameters:
    joints:
      - omni_wheel_joint_1
      - omni_wheel_joint_2
      - omni_wheel_joint_3