<?xml version="1.0"?>
<package format="3">
  <name>omnibot_firmware</name>
  <version>0.1.0</version>
  <description>Omnidirectional robot hardware interface for ROS 2 Jazzy.</description>

  <maintainer email="mateus.oliveira@ee.ufcg.edu.br">Mateus Oliveira</maintainer>
  <license>MIT</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core dependencies -->
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>libserial-dev</depend>

  <!-- Test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
